services:
  - type: web
    name: mosaverse-backend
    env: python
    region: singapore
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: gunicorn config.wsgi --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: mosaverse-db
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false

databases:
  - name: mosaverse-db
    plan: free
    region: singapore
    databaseName: mosaverse
    ipAllowList: []
