# Generated by Django 5.2.15 on 2026-06-09 15:10

import apps.designs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='image',
            field=models.ImageField(upload_to='designs/%Y/%m/', validators=[apps.designs.validators.validate_image_file]),
        ),
    ]
