# Generated by Django 5.0.14 on 2026-06-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("designs", "0002_alter_design_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="design",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
